version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourPassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  users_service:
    build: ./users_service
    ports:
      - "8002:8002"
    depends_on:
      - sqlserver
    environment:
      - DATABASE_URL=mssql+pyodbc://sa:Password1234@db:1433/YourDB?driver=ODBC+Driver+17+for+SQL+Server
      - PYTHONPATH=/app
      
volumes:
  sqlserver_data:
