version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourPassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  login_service:
    build: ./login_service
    ports:
      - "8001:8001"
    depends_on:
      - sqlserver
    environment:
      DATABASE_URL: "mssql+pyodbc://sa:YourPassword@sqlserver:1433/your_db?driver=ODBC+Driver+17+for+SQL+Server"

  users_service:
    build: ./users_service
    ports:
      - "8002:8002"
    depends_on:
      - sqlserver
    environment:
      DATABASE_URL: "mssql+pyodbc://sa:YourPassword@sqlserver:1433/your_db?driver=ODBC+Driver+17+for+SQL+Server"

  posts_service:
    build: ./posts_service
    ports:
      - "8003:8003"
    depends_on:
      - sqlserver
    environment:
      DATABASE_URL: "mssql+pyodbc://sa:YourPassword@sqlserver:1433/your_db?driver=ODBC+Driver+17+for+SQL+Server"

  bff_service:
    build: ./bff_service
    ports:
      - "8004:8004"
    depends_on:
      - login_service
      - users_service
      - posts_service

volumes:
  sqlserver_data:
